# -*- coding: utf-8 -*-
"""langgraph orchestration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9_RpLRMc02HZNv3fqXPEaCSzytX6hg8
"""

!pip install -q langgraph langchain-google-genai fastapi uvicorn pyngrok nest-asyncio pydantic

# =============================================================================
# LANGGRAPH ORCHESTRATION (API-Ready)
# =============================================================================
import os
import json
import operator
from typing import TypedDict, Annotated
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt, Command
from langchain_google_genai import ChatGoogleGenerativeAI

os.environ["GEMINI_API_KEY"] = '.....'
# Initialize Gemini (Forcing JSON output)
llm = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite-preview",
    google_api_key=os.environ["GEMINI_API_KEY"],
    temperature=0.2,
    model_kwargs={"response_mime_type": "application/json"}
)

# 1. STATE
class RestaurantState(TypedDict):
    messages: Annotated[list[dict], operator.add]
    original_query: str
    cuisine: list[str]
    vibe: list[str]
    price_range: int | None
    party_size: int | None
    group_type: str | None
    dietary: list[str]
    must_have: list[str]
    avoid: list[str]
    neighborhood_or_landmark: str | None
    city: str
    open_requirement: str
    is_complete: bool
    followup_question: str | None
    missing_fields: list[str]
    followup_count: int
    final_recommendations: list[dict]
    error: str | None

def get_default_state() -> RestaurantState:
    return {
        "messages": [], "original_query": "", "cuisine": [], "vibe": [],
        "price_range": None, "party_size": None, "group_type": None,
        "dietary": [], "must_have": [], "avoid": [],
        "neighborhood_or_landmark": None, "city": "Philadelphia",
        "open_requirement": "none", "is_complete": False,
        "followup_question": None, "missing_fields": [],
        "followup_count": 0, "final_recommendations": [], "error": None
    }

# 2. NODES
def parse_input(state: RestaurantState) -> RestaurantState:
    latest_message = next((msg["content"] for msg in reversed(state["messages"]) if msg["role"] == "user"), "")
    if not latest_message: return state
    if not state["original_query"]: state["original_query"] = latest_message

    prompt = f"""Extract structured attributes from the user message.
    User message: "{latest_message}"
    Return ONLY a valid JSON object with keys: cuisine (list), vibe (list), price_range (int 1-4 or null), party_size, group_type, dietary, must_have, avoid."""

    try:
        response = llm.invoke(prompt)

        # --- THE FIX: Safely handle if LangChain returns a list ---
        raw_content = response.content
        if isinstance(raw_content, list):
            # Pull the text out of the list
            raw_content = raw_content[0]["text"] if isinstance(raw_content[0], dict) else str(raw_content[0])

        raw = str(raw_content).strip().replace("```json", "").replace("```", "").strip()
        parsed = json.loads(raw)

        for key in ["cuisine", "vibe", "price_range", "party_size", "group_type", "dietary", "must_have", "avoid"]:
            if parsed.get(key) is not None and parsed.get(key) != []:
                state[key] = parsed[key]
    except Exception as e:
        print(f"Parse Error: {e}")
    return state

def check_completeness(state: RestaurantState) -> RestaurantState:
    missing = []
    if not state["cuisine"]: missing.append("cuisine")
    if state["price_range"] is None: missing.append("price_range")
    state["missing_fields"] = missing
    state["is_complete"] = len(missing) == 0

    # FIX: Define the question HERE so it saves to the state before the graph pauses!
    if not state["is_complete"]:
        questions = {
            "cuisine": "What kind of food or cuisine are you in the mood for?",
            "price_range": "What price range are you thinking? ($, $$, $$$, or $$$$)"
        }
        state["followup_question"] = next((questions[f] for f in ["cuisine", "price_range"] if f in missing), "Can you tell me more about what you want?")
    else:
        state["followup_question"] = None

    return state

def ask_followup(state: RestaurantState) -> RestaurantState:
    # We grab the question we already saved in the previous node
    question = state["followup_question"]
    state["followup_count"] = state.get("followup_count", 0) + 1

    # Pause the graph and wait for the frontend!
    user_reply = interrupt(question)
    return {"messages": [{"role": "user", "content": user_reply}]}

def retrieve(state: RestaurantState) -> RestaurantState:
    try:
        # Calls your existing retrieve_and_synthesize function!
        state["final_recommendations"] = retrieve_and_synthesize(state)
        state["error"] = None
    except Exception as e:
        state["error"] = str(e)
    return state

def format_response(state: RestaurantState) -> RestaurantState:
    return state # Pass-through for the API

def route_after_completeness_check(state: RestaurantState) -> str:
    if state.get("followup_count", 0) >= 3 or state["is_complete"]: return "retrieve"
    return "ask_followup"

# 3. BUILD GRAPH
builder = StateGraph(RestaurantState)
builder.add_node("parse_input", parse_input)
builder.add_node("check_completeness", check_completeness)
builder.add_node("ask_followup", ask_followup)
builder.add_node("retrieve", retrieve)
builder.add_node("format_response", format_response)

builder.add_edge(START, "parse_input")
builder.add_edge("parse_input", "check_completeness")
builder.add_conditional_edges("check_completeness", route_after_completeness_check, {"ask_followup": "ask_followup", "retrieve": "retrieve"})
builder.add_edge("ask_followup", "parse_input") # Loops back to read answer
builder.add_edge("retrieve", "format_response")
builder.add_edge("format_response", END)

graph = builder.compile(checkpointer=MemorySaver())

# 4. CHAT RUNNER (Returns the exact Frontend JSON Contract)
def run_conversation(user_message: str, graph, thread_id: str = "default") -> dict:
    config = {"configurable": {"thread_id": thread_id}}
    current_state = graph.get_state(config)

    if current_state.next == () or current_state.values == {}:
        initial_state = get_default_state()
        initial_state["messages"] = [{"role": "user", "content": user_message}]
        result = graph.invoke(initial_state, config)
    else:
        result = graph.invoke(Command(resume=user_message), config)

    api_response = {
        "matched_community": " & ".join(result.get("cuisine", [])) if result.get("cuisine") else "Global Search",
        "city": result.get("city", "Philadelphia"),
        "restaurants": result.get("final_recommendations", []),
        "follow_up_question": result.get("followup_question", None)
    }

    if result.get("is_complete") and result.get("final_recommendations"):
         api_response["follow_up_question"] = None

    return api_response

# =============================================================================
# MAGIC COLAB SERVER (FastAPI + Ngrok + Threading + CORS + Sessions)
# =============================================================================
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyngrok import ngrok
import uvicorn
import threading
import time

app = FastAPI()

# --- THE FIX 1: CORS for Web Browsers ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- THE FIX 2: Accept thread_id from the frontend ---
class ChatRequest(BaseModel):
    prompt: str
    thread_id: str = "default"

@app.post("/recommend")
def recommend(body: ChatRequest):
    print(f"\n📞 RECEIVED FRONTEND REQUEST: '{body.prompt}' (Thread: {body.thread_id})")
    # We pass her specific thread_id into your LangGraph runner!
    return run_conversation(body.prompt, graph, thread_id=body.thread_id)

# 🛑 PASTE YOUR NGROK AUTHTOKEN HERE:
NGROK_TOKEN = "....x"

ngrok.set_auth_token(NGROK_TOKEN)
for tunnel in ngrok.get_tunnels():
    ngrok.disconnect(tunnel.public_url)

public_url = ngrok.connect(8000).public_url

print("\n" + "="*70)
print("🚀 API IS LIVE WITH CORS & SESSIONS ENABLED!")
print(f"👉 {public_url}/recommend")
print("="*70 + "\n")

def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)

server_thread = threading.Thread(target=run_server, daemon=True)
server_thread.start()
print("🛡️ Server is locked and staying alive. Do not stop this cell!")
try:
    while True:
        time.sleep(10) # This keeps the cell 'Running' so the tunnel stays open
except KeyboardInterrupt:
    print("Stopping server...")

import subprocess

# 1. Get and print the IP immediately
ip = subprocess.check_output(["curl", "-s", "ifconfig.me"]).decode("utf-8")
print(f"🔑 YOUR TUNNEL PASSWORD (IP) IS: {ip}")
print("-" * 30)

# 2. Start the tunnel
print("🚀 STARTING TUNNEL... (Check below for your URL)")
!lt --port 8000