# -*- coding: utf-8 -*-
"""recommender RAG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1ynaGCJJlNf5OoiCHjYx6MWEzWhP_hr
"""

!pip install chromadb sentence-transformers pandas numpy tqdm torch

pip install google-genai

# 1. Mount Google Drive to Colab
from google.colab import drive
drive.mount('/content/drive')

import chromadb
import os

# 2. Point to the folder in the "home" of your Google Drive
# Make sure the folder name exactly matches what is in your Drive
CHROMA_PATH = "/content/drive/MyDrive/yelp_chromadb"

# Let's verify the folder and the sqlite file are actually there
if os.path.exists(CHROMA_PATH) and "chroma.sqlite3" in os.listdir(CHROMA_PATH):
    print(f"\n✅ Found the database folder at: {CHROMA_PATH}")

    # 3. Connect to ChromaDB
    client = chromadb.PersistentClient(path=CHROMA_PATH)
    COLLECTION_NAME = "philadelphia_restaurant_reviews"

    try:
        collection = client.get_collection(name=COLLECTION_NAME)
        print(f"Successfully connected to collection: {collection.name}")
        print(f"Total reviews in database: {collection.count()}")

        # Peek at the metadata so we know exactly what columns Person 3 gave us
        sample = collection.peek(1)
        print("\n--- Sample Metadata ---")
        print(sample['metadatas'][0])

    except Exception as e:
        print(f" Connected to DB, but error getting collection: {e}")

else:
    print(f"\n Could not find 'chroma.sqlite3' inside {CHROMA_PATH}.")
    print("Let's check what folders are actually sitting in your MyDrive home directory:")
    print(os.listdir("/content/drive/MyDrive/"))

import pandas as pd

# 1. Load the summary CSV from your Drive (adjust path if needed)
SUMMARY_CSV_PATH = os.path.join(CHROMA_PATH,'restaurant_community_summary_manual.csv')
MAPPING_CSV_PATH = os.path.join(CHROMA_PATH,'restaurant_communities_manual.csv')

# Load them into pandas DataFrames
summary_df = pd.read_csv(SUMMARY_CSV_PATH)
mapping_df = pd.read_csv(MAPPING_CSV_PATH)

summary_df

mapping_df.head()

def get_primary_community_ids(query: dict) -> list[str]:
    """
    Finds ALL communities that match the requested cuisine using a flexible substring match.
    Returns a combined list of business_ids belonging to those primary communities.
    """
    cuisines = [c.lower() for c in query.get("cuisine", [])]

    if not cuisines:
        print("No cuisine provided. Defaulting to global search.")
        return []

    matched_communities = []

    # Score each community and keep ALL that have at least 1 match
    for _, row in summary_df.iterrows():
        comm_id = int(row["community_id"])

        if comm_id == -1:
            continue

        tags_raw = str(row.get("top_5_tags", "")).lower()

        # Check if any user cuisine word is in the community's tags
        score = sum(1 for c in cuisines if c in tags_raw or tags_raw.find(c) != -1)

        if score > 0:
            matched_communities.append(comm_id)

    # If we found matching communities, get ALL their business IDs
    if matched_communities:
        print(f"Matched Cuisine to Community IDs: {matched_communities}")

        # Use .isin() to grab restaurants from all matching communities
        business_ids = mapping_df[mapping_df["community_id"].isin(matched_communities)]["business_id"].tolist()
        print(f"Found {len(business_ids)} primary restaurants across these communities.")

        return business_ids

    print("No specific community matched the cuisine. Defaulting to global search.")
    return []

from sentence_transformers import SentenceTransformer
import chromadb

# 1. Load the embedding model (Person 3 used all-MiniLM-L6-v2)
print("Loading embedding model...")
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

def group_and_rank_reviews(chroma_results, min_similarity=0.3):
    """
    Takes ChromaDB results, groups chunks by restaurant, and scores them.
    Score = (Number of reviews matching vibe) * (Restaurant Star Rating)
    """
    restaurants = {}

    # Chroma returns lists of lists. We grab the first index [0]
    if not chroma_results or not chroma_results['documents'] or len(chroma_results['documents'][0]) == 0:
        return []

    docs = chroma_results['documents'][0]
    metas = chroma_results['metadatas'][0]
    distances = chroma_results['distances'][0]

    for doc, meta, dist in zip(docs, metas, distances):
        # Convert distance to similarity (Assuming Cosine distance: 1 - dist = similarity)
        similarity = 1 - dist

        # Only keep reviews that actually match the user's vibe well
        if similarity < min_similarity:
            continue

        b_id = meta['business_id']
        if b_id not in restaurants:
            restaurants[b_id] = {
                "business_id": b_id,
                "restaurant_name": meta.get("restaurant_name", "Unknown"),
                "stars": meta.get("rating", 0.0), # Note: using 'rating' from your sample metadata
                "price_range": meta.get("price_range", 2),
                "hit_count": 0,
                "reviews": []
            }

        restaurants[b_id]["hit_count"] += 1
        restaurants[b_id]["reviews"].append(doc)

    # Calculate final score: (Hits) * (Stars)
    ranked_list = list(restaurants.values())
    for r in ranked_list:
        r["final_score"] = r["hit_count"] * r["stars"]

    # Sort highest score first
    ranked_list.sort(key=lambda x: x["final_score"], reverse=True)
    return ranked_list

def two_step_retrieval(query_dict: dict, primary_business_ids: list[str]) -> dict:
    cuisines = " ".join(query_dict.get("cuisine", []))
    raw_query = query_dict.get("original_query", " ".join(query_dict.get("vibe", [])))

    search_text = f"{cuisines} food. {raw_query}"
    query_vector = embedding_model.encode(search_text).tolist()
    user_price = query_dict.get("price_range", 2)

    top_primary = []

    # === FIX: Only run Primary Search if we actually have community IDs ===
    if primary_business_ids:
        primary_where = {
            "$and": [
                {"business_id": {"$in": primary_business_ids}},
                {"price_range": {"$eq": user_price}},
                {"rating": {"$gte": 3.5}}
            ]
        }
        primary_results = collection.query(
            query_embeddings=[query_vector], n_results=30, where=primary_where, include=["documents", "metadatas", "distances"]
        )
        top_primary = group_and_rank_reviews(primary_results)[:6]

    # === FIX: Safe Wildcard Search ===
    if primary_business_ids:
        wildcard_where = {
            "$and": [
                {"business_id": {"$nin": primary_business_ids}},
                {"price_range": {"$eq": user_price}},
                {"rating": {"$gte": 4.0}}
            ]
        }
    else:
        # If no cuisine was given, search the entire city!
        wildcard_where = {
            "$and": [
                {"price_range": {"$eq": user_price}},
                {"rating": {"$gte": 4.0}}
            ]
        }

    wildcard_results = collection.query(
        query_embeddings=[query_vector], n_results=20, where=wildcard_where, include=["documents", "metadatas", "distances"]
    )

    # If there were no primary matches, let the wildcards take all 5 slots
    slots_to_fill = 4 if primary_business_ids else 5
    top_wildcards = group_and_rank_reviews(wildcard_results)[:slots_to_fill]

    return {"primary_recommendations": top_primary, "wildcard_recommendations": top_wildcards}

import os
import json
from google import genai

# Safely pull your Gemini key from Colab secrets
os.environ["GEMINI_API_KEY"] = '.....PjnqCk'

# Initialize the Gemini client
gemini_client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

def synthesize_with_llm(retrieved_data: dict, query_dict: dict) -> list[dict]:
    print("Synthesizing results with Gemini...")

    context_text = "=== PRIMARY RECOMMENDATIONS (Safe Bets) ===\n"
    for r in retrieved_data["primary_recommendations"]:
        reviews_combined = " | ".join(r["reviews"][:10])
        context_text += f"Restaurant: {r['restaurant_name']} (ID: {r['business_id']})\nType: primary\nStars: {r['stars']} | Semantic Rank Score: {r['final_score']}\nReviews: {reviews_combined}\n\n"

    context_text += "=== WILDCARD RECOMMENDATIONS (Surprises) ===\n"
    for r in retrieved_data["wildcard_recommendations"]:
        reviews_combined = " | ".join(r["reviews"][:5])
        context_text += f"Restaurant: {r['restaurant_name']} (ID: {r['business_id']})\nType: wildcard\nStars: {r['stars']} | Semantic Rank Score: {r['final_score']}\nReviews: {reviews_combined}\n\n"

    pref_summary = f"""
    Raw User Request: "{query_dict.get('original_query', 'N/A')}"
    Cuisine: {query_dict.get('cuisine', 'any')}
    Vibe: {query_dict.get('vibe', 'any')}
    Price Range: {'$' * query_dict.get('price_range', 2)}
    Explicitly Avoid: {query_dict.get('avoid', 'none')}
    """

    # --- NEW CHANGE: Updated Prompt Instructions ---
    prompt = f"""You are a brilliant, strict restaurant recommendation assistant.
    I have provided a list of Primary recommendations and Wildcard recommendations.
    These restaurants have ALREADY been strictly filtered by a semantic AI database.
    If the user is asking you for recommendations, based on their input what would you recommend them from provided recommendations?

    Your instructions:
    1. Read the "Raw User Request" and "Cuisine" carefully.
    2. PRIMARY recommendations MUST match the requested Cuisine. If a primary restaurant serves completely the wrong cuisine (e.g., French when they asked for Italian), drop it.
    3. ONLY drop a restaurant for negative constraints if its reviews explicitly violate an 'Avoid' rule. E.g.,Do NOT drop a restaurant just because the review doesn't mention spice levels. Trust the 'Semantic Rank Score'.
    4. You MUST return 5 restaurants (Aim for 3 Primary and 2 Wildcard). If there aren't 5 perfect ones, return the valid ones.

    For Wildcard restaurants, your `why_it_fits` summary MUST explicitly frame it as a fun alternative (e.g. "If you want to step away from Italian...").
    CRITICAL: Ensure your output is perfectly valid JSON. If you use quotes inside your text strings, you MUST escape them (e.g., \").

    Return a JSON array where each object has exactly these keys:
    - "restaurant_name" (string)
    - "business_id" (string)
    - "stars" (float)
    - "price_range" (int)
    - "recommendation_type" (string, either "primary" or "wildcard")
    - "why_it_fits" (string, 1-2 sentences)
    - "highlight" (string, a standout quote/detail from reviews)

    Preferences:
    {pref_summary}

    Context:
    {context_text}
    """
    # -----------------------------------------------

    response = gemini_client.models.generate_content(
        model='gemini-3.1-flash-lite-preview',
        contents=prompt,
        config={
            'response_mime_type': 'application/json'
        }
    )

    try:
        return json.loads(response.text)
    except Exception as e:
        print(f"Error parsing Gemini output: {e}")
        return []

def retrieve_and_synthesize(query_dict: dict) -> list[dict]:
    print("Starting RAG Pipeline...")

    # 1. Graph Routing
    primary_ids = get_primary_community_ids(query_dict)

    # 2. Semantic Search
    retrieved_data = two_step_retrieval(query_dict, primary_ids)

    print("\n" + "="*50)
    print("X-RAY: WHAT CHROMADB FOUND (BEFORE GEMINI)")
    print("="*50)

    print("PRIMARY POOL (Safe Bets):")
    if not retrieved_data["primary_recommendations"]:
        print("   None found!")
    for i, r in enumerate(retrieved_data["primary_recommendations"]):
        print(f"   {i+1}. {r['restaurant_name']} | {r['stars']} | Hits: {r['hit_count']} | Score: {r['final_score']}")

    print("\nWILDCARD POOL (Surprises):")
    if not retrieved_data["wildcard_recommendations"]:
        print("   None found!")
    for i, r in enumerate(retrieved_data["wildcard_recommendations"]):
        print(f"   {i+1}. {r['restaurant_name']} | {r['stars']} | Hits: {r['hit_count']} | Score: {r['final_score']}")
    print("="*50 + "\n")
    # ==========================================
    total = len(retrieved_data["primary_recommendations"]) + len(retrieved_data["wildcard_recommendations"])

    if total == 0:
        return {"error": "No restaurants found matching your preferences. Try adjusting your price range or cuisine."}

    # 3. LLM Synthesis
    final_output = synthesize_with_llm(retrieved_data, query_dict)

    print(" Pipeline Complete.")
    return final_output

test_query = {
    "cuisine": ["Asian", "Thai"],
    "vibe": ["quiet","pleasant"],
    "original_query": "I want to have thai food with my girfliend for a data night in a quiet restaurant",
    "price_range": 2
}
retrieve_and_synthesize(test_query)

test_2 = {
    "cuisine": ["Italian", "drinks"],
    "vibe": ["quiet", "romantic"],
    "price_range": 2,
    "group_type": "couple",
    "party_size": 2,
    "dietary": [],
    "must_have": [],
    "avoid": ["loud"],
    "neighborhood_or_landmark": None,
    "city": "Philadelphia",
    "open_requirement": "none",
    "original_query": "something calm and not too spicy for a date night, mid range"  # raw user query
}
retrieve_and_synthesize(test_2)

